import Head from 'next/head';
import styles from './Main_Layout.module.css';
import { ReactNode } from "react";

interface LayoutProps {
  children: ReactNode;
}

export default function Main_Layout({ children }: LayoutProps) {
    return (
        <>
            <Head>
                <title>PacePilot. Dein Guide zum perfekten Halbmarathon-Lauf-Tempo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"/>
            </Head>
            {/* <header className="text-bg-light text-center py-3">
                <div className="container">
                    <h1>PacePilot - Dein Guide zum perfekten Lauf-Tempo</h1>
                </div>
            </header> */}
            <div className="layout">{children}               
            </div>
            {/* <nav className="navbar navbar-light fixed-bottom bg-light">
                <div className="container-fluid justify-content-around">
                    <div className="text-center">
                        <i className="bi bi-house" style={{ fontSize: '24px' }}></i>
                        <div style={{ fontSize: '10px' }}>Dein Plan</div>
                    </div>
                    <div className="text-center">
                        <i className="bi bi-calendar" style={{ fontSize: '24px' }}></i>
                        <div style={{ fontSize: '10px' }}>Aktuelle Woche</div>
                    </div>
                    <div className="text-center">
                        <i className="bi bi-gear" style={{ fontSize: '24px' }}></i>
                        <div style={{ fontSize: '10px' }}>Einstellungen</div>
                    </div>
                    <div className="text-center">
                        <i className="bi bi-info-circle" style={{ fontSize: '24px' }}></i>
                        <div style={{ fontSize: '10px' }}>FAQ</div>
                    </div>
                </div>
            </nav> */}
        </>
    );
}