import Head from 'next/head';
import { ReactNode } from "react";

interface LayoutProps {
  children: ReactNode;
}

export default function Main_Layout({ children }: LayoutProps) {
    return (
        <>
            <Head>
                <title>PacePilot. Dein Guide zum perfekten Halbmarathon-Lauf-Tempo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"/>
            </Head>
            <div className="layout">{children}</div>
        </>
    );
}